var table_data = [
	{
		"tableManagerId" : 1,
		"tableName" : "FactGoodsSearchDaySum",
		"tableType" : "事实表",
		"dataLevel" : "日汇总",
		"procName" : "PrGoodsSearchDaySum",
		"note" : "会员找货日汇总表",
		"inputMan" : "刘圣其",
		"inputDate" : "0000-00-00 00:00:00",
		"updateMan" : "刘圣其",
		"updateDate" : "0000-00-00 00:00:00",
		"businessType" : ""
	},
	{
		"tableManagerId" : 2,
		"tableName" : "FactTrade",
		"tableType" : "事实表",
		"dataLevel" : "月汇总",
		"procName" : "PrDistributionFact",
		"note" : "配货成交明细表",
		"inputMan" : "刘圣其",
		"inputDate" : "0000-00-00 00:00:00",
		"updateMan" : "刘圣其",
		"updateDate" : "0000-00-00 00:00:00",
		"businessType" : ""
	},
	{
		"tableManagerId" : 3,
		"tableName" : "FactTradeShipperDaySum",
		"tableType" : "事实表",
		"dataLevel" : "日汇总",
		"procName" : "PrTradeDaySum",
		"note" : "配货货主成交日汇总表",
		"inputMan" : "刘圣其",
		"inputDate" : "0000-00-00 00:00:00",
		"updateMan" : "刘圣其",
		"updateDate" : "0000-00-00 00:00:00",
		"businessType" : ""
	},
	{
		"tableManagerId" : 4,
		"tableName" : "QLogApiExecTime",
		"tableType" : "事实表",
		"dataLevel" : "日汇总",
		"procName" : "",
		"note" : "由日志中统计的各包接口执行耗时",
		"inputMan" : "何敏",
		"inputDate" : "2015-12-02 10:18:32",
		"updateMan" : "何敏",
		"updateDate" : "2015-12-02 10:18:32",
		"businessType" : ""
	},
	{
		"tableManagerId" : 5,
		"tableName" : "FactTradeDriverDaySum",
		"tableType" : "事实表",
		"dataLevel" : "日汇总",
		"procName" : "PrTradeDaySum",
		"note" : "配货货主成交日汇总表",
		"inputMan" : "刘圣其",
		"inputDate" : "0000-00-00 00:00:00",
		"updateMan" : "刘圣其",
		"updateDate" : "0000-00-00 00:00:00",
		"businessType" : ""
	},
	{
		"tableManagerId" : 6,
		"tableName" : "FactTradeShipperDriverDaySum",
		"tableType" : "事实表",
		"dataLevel" : "日汇总",
		"procName" : "PrTradeDaySum",
		"note" : "配货货主和司机成交日汇总表",
		"inputMan" : "刘圣其",
		"inputDate" : "0000-00-00 00:00:00",
		"updateMan" : "刘圣其",
		"updateDate" : "0000-00-00 00:00:00",
		"businessType" : ""
	},
	{
		"tableManagerId" : 7,
		"tableName" : "QLogApiExecTimePercentile",
		"tableType" : "查询表",
		"dataLevel" : "月汇总",
		"procName" : "",
		"note" : "由日志中统计的各包接口执行速度",
		"inputMan" : "何敏",
		"inputDate" : "2015-12-02 10:18:32",
		"updateMan" : "何敏",
		"updateDate" : "2015-12-02 10:18:32",
		"businessType" : ""
	},
	{
		"tableManagerId" : 8,
		"tableName" : "FactLogApiUrlDict",
		"tableType" : "查询表",
		"dataLevel" : "原子表",
		"procName" : "",
		"note" : "包接口地址URL的中文翻译字典",
		"inputMan" : "何敏",
		"inputDate" : "2015-12-02 10:30:34",
		"updateMan" : "何敏",
		"updateDate" : "2015-12-02 10:30:43",
		"businessType" : ""
	},
	{
		"tableManagerId" : 9,
		"tableName" : "CdYBOrderBillDtl",
		"tableType" : "查询表",
		"dataLevel" : "原子表",
		"procName" : "PrYbOrderBillDtl",
		"note" : "运宝网订单明细表，用于运宝网接口服务",
		"inputMan" : "刘圣其",
		"inputDate" : "0000-00-00 00:00:00",
		"updateMan" : "刘圣其",
		"updateDate" : "0000-00-00 00:00:00",
		"businessType" : ""
	},
	{
		"tableManagerId" : 10,
		"tableName" : "CdYBOrderDaySum",
		"tableType" : "查询表",
		"dataLevel" : "日汇总",
		"procName" : "PrYbOrderBillDtl",
		"note" : "运宝网订单日汇总表，用于运宝网接口服务",
		"inputMan" : "刘圣其",
		"inputDate" : "0000-00-00 00:00:00",
		"updateMan" : "刘圣其",
		"updateDate" : "0000-00-00 00:00:00",
		"businessType" : ""
	},
	{
		"tableManagerId" : 11,
		"tableName" : "QPartyEarliestLoginDate",
		"tableType" : "中间表",
		"dataLevel" : "原子表",
		"procName" : "PrProcessPortraitBasicData",
		"note" : "会员首次登陆时间",
		"inputMan" : "刘圣其",
		"inputDate" : "0000-00-00 00:00:00",
		"updateMan" : "刘圣其",
		"updateDate" : "0000-00-00 00:00:00",
		"businessType" : ""
	},
	{
		"tableManagerId" : 12,
		"tableName" : "QPartyEarliestFindDate",
		"tableType" : "中间表",
		"dataLevel" : "原子表",
		"procName" : "PrProcessPortraitBasicData",
		"note" : "会员首次找货时间",
		"inputMan" : "刘圣其",
		"inputDate" : "0000-00-00 00:00:00",
		"updateMan" : "刘圣其",
		"updateDate" : "0000-00-00 00:00:00",
		"businessType" : ""
	},
	{
		"tableManagerId" : 13,
		"tableName" : "QPartyEarliestTradeDate",
		"tableType" : "中间表",
		"dataLevel" : "原子表",
		"procName" : "PrProcessPortraitBasicData",
		"note" : "会员首次交易时间",
		"inputMan" : "刘圣其",
		"inputDate" : "0000-00-00 00:00:00",
		"updateMan" : "刘圣其",
		"updateDate" : "0000-00-00 00:00:00",
		"businessType" : ""
	},
	{
		"tableManagerId" : 14,
		"tableName" : "QPartyUseRedPacket",
		"tableType" : "中间表",
		"dataLevel" : "原子表",
		"procName" : "PrProcessPortraitBasicData",
		"note" : "会员首次和最近使用红包时间",
		"inputMan" : "刘圣其",
		"inputDate" : "0000-00-00 00:00:00",
		"updateMan" : "刘圣其",
		"updateDate" : "0000-00-00 00:00:00",
		"businessType" : ""
	},
	{
		"tableManagerId" : 15,
		"tableName" : "QPartyLastLocation",
		"tableType" : "中间表",
		"dataLevel" : "原子表",
		"procName" : "PrProcessPortraitBasicData",
		"note" : "会员最近所在区域  根据Lbs结算结果而来",
		"inputMan" : "刘圣其",
		"inputDate" : "0000-00-00 00:00:00",
		"updateMan" : "刘圣其",
		"updateDate" : "0000-00-00 00:00:00",
		"businessType" : ""
	},
	{
		"tableManagerId" : 16,
		"tableName" : "QPartyCarWayProvinceCity",
		"tableType" : "中间表",
		"dataLevel" : "原子表",
		"procName" : "PrProcessPortraitBasicData",
		"note" : "会员按路线的找货次数",
		"inputMan" : "刘圣其",
		"inputDate" : "0000-00-00 00:00:00",
		"updateMan" : "刘圣其",
		"updateDate" : "0000-00-00 00:00:00",
		"businessType" : ""
	},
	{
		"tableManagerId" : 17,
		"tableName" : "PartyDevelopmentTotal_0914",
		"tableType" : "查询表",
		"dataLevel" : "日汇总",
		"procName" : "p_report_partydevelopmenttotal_recently5days_0914",
		"note" : "会员发展统计表",
		"inputMan" : "王聪",
		"inputDate" : "2015-12-02 01:44:26",
		"updateMan" : "",
		"updateDate" : "2015-12-02 01:44:26",
		"businessType" : ""
	},
	{
		"tableManagerId" : 18,
		"tableName" : "FactMemberGiftDaySum",
		"tableType" : "事实表",
		"dataLevel" : "日汇总",
		"procName" : "PrGiftFact",
		"note" : "赠品记录日汇总表",
		"inputMan" : "刘圣其",
		"inputDate" : "2015-12-02 03:06:55",
		"updateMan" : "刘圣其",
		"updateDate" : "2015-12-02 03:06:55",
		"businessType" : "陆鲸"
	},
	{
		"tableManagerId" : 19,
		"tableName" : "QPartyAttentionLine",
		"tableType" : "查询表",
		"dataLevel" : "日汇总",
		"procName" : "PrPartyAttentionLine",
		"note" : "关注路线",
		"inputMan" : "刘圣其",
		"inputDate" : "2015-12-03 12:47:28",
		"updateMan" : "刘圣其",
		"updateDate" : "2015-12-03 12:47:28",
		"businessType" : ""
	},
	{
		"tableManagerId" : 20,
		"tableName" : "QDepartmentPerformance",
		"tableType" : "查询表",
		"dataLevel" : "日汇总",
		"procName" : "p_report_qdepartmentperformance",
		"note" : "部门业绩日汇总",
		"inputMan" : "王聪",
		"inputDate" : "2015-12-08 02:02:33",
		"updateMan" : "王聪",
		"updateDate" : "2015-12-08 02:02:33",
		"businessType" : "陆鲸"
	},
	{
		"tableManagerId" : 21,
		"tableName" : "QDepartmentPerformanceByMonth",
		"tableType" : "查询表",
		"dataLevel" : "月汇总",
		"procName" : "p_report_qdepartmentperformancebymonth",
		"note" : "部门业绩月汇总",
		"inputMan" : "王聪",
		"inputDate" : "2015-12-08 02:02:33",
		"updateMan" : "王聪",
		"updateDate" : "2015-12-08 02:02:33",
		"businessType" : "陆鲸"
	},
	{
		"tableManagerId" : 22,
		"tableName" : "QDepartmentPerformanceByQuarter",
		"tableType" : "查询表",
		"dataLevel" : "全量汇总",
		"procName" : "p_report_qdepartmentperformancebyquarter",
		"note" : "部门业绩季度汇总",
		"inputMan" : "王聪",
		"inputDate" : "2015-12-08 02:02:33",
		"updateMan" : "王聪",
		"updateDate" : "2015-12-08 02:02:33",
		"businessType" : "陆鲸"
	},
	{
		"tableManagerId" : 23,
		"tableName" : "DimSysRegion",
		"tableType" : "维度表",
		"dataLevel" : "全量汇总",
		"procName" : "dim_report_DimSysRegion",
		"note" : "城市权限维度表",
		"inputMan" : "王健",
		"inputDate" : "0000-00-00 00:00:00",
		"updateMan" : "王健",
		"updateDate" : "0000-00-00 00:00:00",
		"businessType" : "陆鲸"
	},
	{
		"tableManagerId" : 24,
		"tableName" : "EmployeePerformance",
		"tableType" : "查询表",
		"dataLevel" : "日汇总",
		"procName" : "p_report_employeeperformance",
		"note" : "员工业绩",
		"inputMan" : "王聪",
		"inputDate" : "2015-12-09 02:36:49",
		"updateMan" : "王聪",
		"updateDate" : "2015-12-09 02:36:49",
		"businessType" : "陆鲸"
	},
	{
		"tableManagerId" : 25,
		"tableName" : "ShipperPerformance",
		"tableType" : "中间表",
		"dataLevel" : "日汇总",
		"procName" : "p_report_shipperperformance",
		"note" : "员工详情",
		"inputMan" : "王聪",
		"inputDate" : "2015-12-09 02:37:37",
		"updateMan" : "王聪",
		"updateDate" : "2015-12-09 02:37:37",
		"businessType" : "陆鲸"
	},
	{
		"tableManagerId" : 26,
		"tableName" : "ShipperPerformanceResult",
		"tableType" : "查询表",
		"dataLevel" : "日汇总",
		"procName" : "p_report_shipperperformanceresult",
		"note" : "员工详情-前置表ShipperPerformance",
		"inputMan" : "王聪",
		"inputDate" : "2015-12-09 02:37:37",
		"updateMan" : "王聪",
		"updateDate" : "2015-12-09 02:37:37",
		"businessType" : "陆鲸"
	},
	{
		"tableManagerId" : 27,
		"tableName" : "QDataPermissionBelong",
		"tableType" : "中间表",
		"dataLevel" : "全量汇总",
		"procName" : "p_report_qdatapermissionbelong",
		"note" : "运营数据权限",
		"inputMan" : "王聪",
		"inputDate" : "2015-12-28 09:31:47",
		"updateMan" : "王聪",
		"updateDate" : "2015-12-28 09:31:47",
		"businessType" : "陆鲸"
	},
	{
		"tableManagerId" : 28,
		"tableName" : "QGoodSourceReleaseCountByDay",
		"tableType" : "查询表",
		"dataLevel" : "日汇总",
		"procName" : "p_report_qgoodsourcereleasecountbyday",
		"note" : "发货按人按日汇总",
		"inputMan" : "王聪",
		"inputDate" : "2016-01-07 04:41:34",
		"updateMan" : "王聪",
		"updateDate" : "2016-01-07 04:41:34",
		"businessType" : "陆鲸"
	},
	{
		"tableManagerId" : 29,
		"tableName" : "QDriverSettlement",
		"tableType" : "中间表",
		"dataLevel" : "全量汇总",
		"procName" : "p_report_qdriversettlement",
		"note" : "发展司机结算汇总",
		"inputMan" : "王聪",
		"inputDate" : "2016-01-08 09:37:27",
		"updateMan" : "王聪",
		"updateDate" : "2016-01-08 09:37:27",
		"businessType" : "陆鲸"
	},
	{
		"tableManagerId" : 30,
		"tableName" : "QShipperSettlement",
		"tableType" : "中间表",
		"dataLevel" : "全量汇总",
		"procName" : "p_report_qshippersettlement",
		"note" : "发展货主结算汇总",
		"inputMan" : "王聪",
		"inputDate" : "2016-01-08 09:37:27",
		"updateMan" : "王聪",
		"updateDate" : "2016-01-08 09:37:27",
		"businessType" : "陆鲸"
	},
	{
		"tableManagerId" : 31,
		"tableName" : "QLoginCheat",
		"tableType" : "中间表",
		"dataLevel" : "周汇总",
		"procName" : "p_report_qlogincheat",
		"note" : "同一手机登录多个账号按周汇总",
		"inputMan" : "王聪",
		"inputDate" : "2016-01-08 10:08:44",
		"updateMan" : "王聪",
		"updateDate" : "2016-01-08 10:08:44",
		"businessType" : "陆鲸"
	},
	{
		"tableManagerId" : 32,
		"tableName" : "QDBOJobCardBelong",
		"tableType" : "查询表",
		"dataLevel" : "原子表",
		"procName" : "p_report_qdbojobcardbelong",
		"note" : "运营根据员工权限推归属",
		"inputMan" : "王聪",
		"inputDate" : "2016-01-21 11:25:31",
		"updateMan" : "王聪",
		"updateDate" : "2016-01-21 11:25:31",
		"businessType" : "陆鲸"
	},
	{
		"tableManagerId" : 33,
		"tableName" : "DimForwarderManagement",
		"tableType" : "维度表",
		"dataLevel" : "",
		"procName" : "PrDimForwarderManagement",
		"note" : "员工货代绑定，主要处理时间问题",
		"inputMan" : "刘圣其",
		"inputDate" : "2016-01-29 01:46:14",
		"updateMan" : "刘圣其",
		"updateDate" : "2016-01-29 01:46:14",
		"businessType" : "陆鲸"
	}
];

